### ISSUE TITLE
onError is not a function

### ISSUE THREAD

**Issue by bumjin1013** [actbase/react-daum-postcode#5]
안녕하세요 코드 사용 중 주소 검색하고 클릭 시 에러가 발생합니다. return 되는 data는 잘 받아들여오는데 아래 에러가 발생하네요 ㅠㅠ

[02:47:45] TypeError: onError is not a function. (In 'onError(e)', 'onError' is undefined)
[2] at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
[2] at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
[2] at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
[2] at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

app.native.js (40:14) 에서 에러가 납니다.

**Comment by bumjin1013** [comment]
앗.. onSelected안에 잘못된 함수를 사용했어서 발생한 오류네요그쪽부분 console.log(e)로 변경해서 다시 사용해보니 에러 찍혀서 수정했습니다 :)
